name: plasmapy

channels:
    - astropy

dependencies:
    - python=3.6
    - astropy
    - matplotlib
    - numpy
    - scipy
    - numpydoc
    - pip:
        - sphinx
        - sphinx-gallery
        - pillow
