name: add comment

on:
  pull_request_target:
    types: [opened]

jobs:
  checklist:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `Thank you for contributing! ✨ PlasmaPy's future depends on contributors like you, so we deeply appreciate it! 🌱

            Please check out our [**contributor guide**](https://docs.plasmapy.org/en/latest/contributing/index.html) to learn more about:

             - [Getting ready to contribute](https://docs.plasmapy.org/en/latest/contributing/getting_ready.html#getting-ready-to-contribute)
             - The [code contribution workflow](https://docs.plasmapy.org/en/latest/contributing/workflow.html#code-contribution-workflow)
             - [Coding guidelines, conventions, and best practices](https://docs.plasmapy.org/en/latest/contributing/coding_guide.html#coding-guide)
             - [Writing documentation](https://docs.plasmapy.org/en/latest/contributing/doc_guide.html#writing-documentation) and [documentation troubleshooting](https://docs.plasmapy.org/en/latest/contributing/doc_guide.html#troubleshooting)
               - PlasmaPy's docs are written in the [reStructuredText]() markup language
             - [Docstrings](https://docs.plasmapy.org/en/latest/contributing/doc_guide.html#docstrings) follow the [numpydoc standard]() (example)
            - [Writing tests](https://docs.plasmapy.org/en/latest/contributing/testing_guide.html#testing-guide)
            - [Adding a changelog entry](https://docs.plasmapy.org/en/latest/contributing/changelog_guide.html#adding-a-changelog-entry)

            Here are some suggestions

             - Here are tips on [writing clean scientific software]().
             - Write short functions that do exactly one thing with no side effects.
             - PlasmaPy's documentation is written in [reStructuredText]() and follows the [numpydoc standard]().
             - Please use SI units within the code, unless there is a strong justification otherwise.
             - When adding a
             - Check the

            When the pre-commit check fails, try commenting on this pull request with \`pre-commit.ci autofix\`. This will automagically fix

            If this is your first contribution to PlasmaPy, please add your name to the author list in [\`docs/about/credits.rst\`]().
          })
