name: add comment

on:
  pull_request_target:
    types: [opened]

jobs:
  checklist:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `Thank you for contributing! ✨ PlasmaPy's future depends on contributors like you, so we deeply appreciate it! 🌱

            [**contributor guide**]: https://docs.plasmapy.org/en/latest/contributing/index.html
            [Getting ready to contribute]: https://docs.plasmapy.org/en/latest/contributing/getting_ready.html#getting-ready-to-contribute
            [code contribution workflow]: https://docs.plasmapy.org/en/latest/contributing/workflow.html#code-contribution-workflow
            [coding tips and guidelines]: https://docs.plasmapy.org/en/latest/contributing/coding_guide.html#coding-guide
            [Writing documentation]: https://docs.plasmapy.org/en/latest/contributing/doc_guide.html#writing-documentation
            [documentation troubleshooting]: https://docs.plasmapy.org/en/latest/contributing/doc_guide.html#troubleshooting
            [Writing tests]: https://docs.plasmapy.org/en/latest/contributing/testing_guide.html#testing-guide
            [add a changelog entry]: https://docs.plasmapy.org/en/latest/contributing/changelog_guide.html#adding-a-changelog-entry
            [online documentation]: https://docs.plasmapy/org/en/latest
            [\`@particle_input\`]: https://docs.plasmapy.org/en/latest/api/plasmapy.particles.decorators.particle_input.html#particle-input
            [\`astropy.units\`]: https://docs.plasmapy.org/en/latest/notebooks/getting_started/units.html#Using-Astropy-Units
            [\`plasmapy.particles\`]: https://docs.plasmapy.org/en/latest/notebooks/getting_started/particles.html#Using-PlasmaPy-Particles
            [reStructuredText]: https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#restructuredtext-primer
            [Docstrings]:
            [numpydoc standard]:
            [example docstring]:

            Don't worry if something broke! We break stuff all the time.   

            Please check out our [**contributor guide**] and [documentation] to learn more about:

             - [Getting ready to contribute]
             - The [code contribution workflow]
             - [Coding tips and guidelines]
             - [Writing documentation] & [documentation troubleshooting]
             - [Writing tests]
             - Using [\`astropy.units\`] and [\`plasmapy.particles\`]

            Please [add a changelog entry], unless this pull request is very minor.

             - Use [\`@particle_input\`] for functions that accept particles as arguments.
             - Use [\`@validate_quantities\`] for functions that accept [\`Quantity\`] objects as

             - PlasmaPy's documentation is written in [reStructuredText].  [Docstrings] follow the [numpydoc standard] ([example docstring]).

             - Please use SI units within the code, unless there is a strong justification otherwise.
             - When adding a
             - Check the

             - Here are tips on [writing clean scientific software]().


            When the pre-commit check fails, try commenting on this pull request with \`pre-commit.ci autofix\`. This will automagically fix

            If this is your first contribution to PlasmaPy, please add your name to the author list in [\`docs/about/credits.rst\`]().
          })
